### PR TITLE
etcd: move scalyr management to AWS adapter

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Turns out we don't use CLM templating at all, just `senza print`. This means that we need to add support for Scalyr stuff directly to CLM.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
@mikkeloscar Sorry about that. :(

**Comment by mikkeloscar** [comment]
@aermakov-zalando would it make sense to still keep the template functions and aim to move towards the template solution in the future?

I still like the idea of eventually getting rid of `senza` with a new improved etcd setup.

**Comment by aermakov-zalando** [comment]
@mikkeloscar Sure, once we switch I'll just put it back into the templates. Or do you want to keep both?

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
