### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mikkeloscar**
Update dependencies as reported by @dependabot including regenerating with new version of go-swagger.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
:+1:

**Comment by linki** [comment]
Sorry, I merged one of the other PRs :facepalm:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
:+1:

**Pull request merged**
