### PR TITLE
Update to Kubernetes v1.27

### PR DESCRIPTION
**Pull request by linki**
Update Kubernetes libraries to 1.27

https://github.bus.zalan.do/teapot/issues/issues/3570

### CODE REVIEW

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
@linki We should also update kubectl (can also be in separate PR ofc.)

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
I'll add it in this PR.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
@linki the DCO check failed FYI

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
