### PR TITLE
Remove Taupage specific code.

### PR DESCRIPTION
**Pull request by gargravarr**
Removes code specific for handling Taupage AMIs (the "horrible hack"), which are not used anymore. 

Signed-off-by: rreis <rodrigo@zalando.de>

### CODE REVIEW

**Comment by gargravarr** [comment]
:+1:

**Comment by katyanna** [comment]
Should this be removed too?
- https://github.com/zalando-incubator/cluster-lifecycle-manager/blob/master/provisioner/aws.go#L487

**Comment by gargravarr** [comment]
:+1:

**Comment by katyanna** [comment]
👍

**Pull request merged**
