### PR TITLE
Update AWS instance types

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Add `c5ad`, `t4g` instances. I've had to patch storage information manually for a couple of those, maybe we should switch away from ec2instances.info.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
> maybe we should switch away from ec2instances.info.

Or contribute the information? :) Unless there is a better source nowadays?

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
@mikkeloscar AWS has some kind of an API for this now, which is used in the CA generator for example.

**Pull request merged**
