### PR TITLE
Switch from glide to dep

### PR DESCRIPTION
**Pull request by linki**
imo, it makes managing the dependencies a little easier than glide by now.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Unrelated, but that coveralls check clearly doesn't work. 100% LOL!

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
Yes :( Maybe https://github.com/lawrencewoodman/roveralls can fix this as well.

**Comment by linki** [comment]
👍

**Pull request merged**
