### PR TITLE
Improve userdata files

### PR DESCRIPTION
**Pull request by aermakov-zalando**
* Use the correct KMS key depending on the pool type
 * Include the cluster ID and the pool kind so it's easier to cleanup later (only if `clm_new_userdata_path` is set to true)

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by aermakov-zalando** [comment]
Argh, wait, this will roll all the nodes.

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
