### PR TITLE
Checking Cluster Registry generated client

### PR DESCRIPTION
**Pull request by mikkeloscar**
This is in order to make the golangci-lint work which depends on all the files being present.

Follow up to #137

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by arjunrn** [comment]
We should also check the `Makefile` in this case so that the client is not generated on every build.

**Comment by mikkeloscar** [comment]
> We should also check the `Makefile` in this case so that the client is not generated on every build.

I think the problem is that when it's checked out with git in the build system, the timestamp of the files might be different which causes make to thing it needs to regenerate. I'm not sure how to prevent this without loosing the dependency when we actually change something locally and wants make to pick it up?

**Comment by linki** [comment]
:+1:

**Comment by njuettner** [comment]
👍

**Comment by njuettner** [comment]
@mikkeloscar 🙏 thanks!

**Pull request merged**
