### PR TITLE
Update instance.json to add new instance types

### PR DESCRIPTION
**Pull request by mikkeloscar**
* Updates `instances.json` to get new AWS instance types which we didn't yet support.
* Regenerates the swagger client for Cluster Registry after changes in #338

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
@mikkeloscar Was our CA fork updated to match?

**Comment by mikkeloscar** [comment]
@aermakov-zalando no, I will do that as well!

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
