### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jonathanbeber**
This commit is the output of `go get -u` and `go mod tidy`.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
We may want to exclude the client-go (+friends) v1.20.x update until we run v1.20. We can do v1.19.9 for now.

**Comment by jonathanbeber** [comment]
Good point, I will revert these

**Comment by jonathanbeber** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
