### PR TITLE
Update client-go/kubectl to Kubernetes v1.25

### PR DESCRIPTION
**Pull request by mikkeloscar**
* Updates k8s.io libraries to Kubernetes v1.25
* Updates other deps to latest version
* Update kubectl to v1.25.16

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
> Coverage decreased (-29.5%) to 23.053%

Coverage is being redesigned in go1.22 and there are a bunch of issues reported, e.g. https://github.com/golang/go/issues/65570
The workaround is to use GOEXPERIMENT=nocoverageredesign to disable new behaviour.

**Comment by mikkeloscar** [comment]
> The workaround is to use GOEXPERIMENT=nocoverageredesign to disable new behaviour.

I added this!

**Comment by mikkeloscar** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
